version: '3'
services:
  app:
    image: elrathor/datacollector
    ports:
      - "80:80"
    volumes:
      - ./data.db:/app/data.db
    environment:
      - BASIC_AUTH_USERNAME=your_username
      - BASIC_AUTH_PASSWORD=your_password